services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile.local
    image: application
    volumes:
      - ./public:/var/www/html
    ports:
      - 8080:80
      - 443:443

      